server:
  port: 8086

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

  datasource:
    url: jdbc:postgresql://localhost:5432/skill_track
    username: postgres
    password: postgres
    hikari:
      schema: notification_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS notification_schema
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true

telegram:
  bot:
    token: #